[package]
name = "lxr"
version = "0.0.1"
authors = ["Alexander <alexander.bifulco@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.6.0"
glutin = "0.21.0"
rand = "0.6.5"
specs = "0.14.3"
smallvec = "0.6.10"
lazy_static = "1.3.0"
libc = "0.2.58"